[package]
name = "homeostat-cli"
version.workspace = true
edition.workspace = true
repository.workspace = true
publish = false

[features]
training = ["dep:homeostat-training"]

[[bin]]
name = "homeostat"
path = "src/main.rs"

[dependencies]
axum.workspace = true
clap.workspace = true
homeostat-training = { path = "../homeostat-training", optional = true }
opentelemetry.workspace = true
opentelemetry-prometheus.workspace = true
opentelemetry_sdk.workspace = true
prometheus.workspace = true
tokio.workspace = true
